spring:
  sql:
    init:
      mode: always
  jpa:
    show-sql: true
  datasource:
    url: "jdbc:postgresql://localhost:${DB_PORT}/${DB_NAME}"
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
server:
  port: 82

twilio:
  account_sid: ${TWILIO_ACCOUNT_SID}
  service_sid: ${TWILIO_SERVICE_SID}
  token: ${TWILIO_TOKEN}
