spring:
  sql:
    init:
      mode: always
  jpa:
    show-sql: true
  datasource:
    url: "jdbc:postgresql://localhost:5432/"
    username: "myusername"
    password: "mypassword"
server:
  port: 82